// <auto-generated />

using System;
using Lawrence.Tsuro.TechTest.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lawrence.Tsuro.TechTest.Entities.Migrations
{
    [ DbContext(typeof(AppContext)) ]
    internal partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
        #pragma warning disable 612, 618
            modelBuilder
               .HasAnnotation("ProductVersion", "3.1.0")
               .HasAnnotation("Relational:MaxIdentifierLength", 128)
               .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lawrence.Tsuro.TechTest.Entities.Address", b =>
                                                                            {
                                                                                b.Property<Guid>("AddressId")
                                                                                 .ValueGeneratedOnAdd()
                                                                                 .HasColumnType("uniqueidentifier");

                                                                                b.Property<string>("City")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("Company")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("County")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("Email")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("Name")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("Phone")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("Postcode")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("Street")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<string>("Surname")
                                                                                 .IsRequired()
                                                                                 .HasColumnType("nvarchar(250)")
                                                                                 .HasMaxLength(250);

                                                                                b.Property<DateTime>("Updated")
                                                                                 .HasColumnType("datetime2");

                                                                                b.HasKey("AddressId");

                                                                                b.ToTable("Addresses");
                                                                            });
        #pragma warning restore 612, 618
        }
    }
}